# Generated by Django 2.2.5 on 2019-09-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tipo_veiculo', models.CharField(max_length=1000, null=True)),
                ('fipe_name', models.CharField(max_length=1000, null=True)),
                ('nome', models.CharField(max_length=1000, null=True)),
                ('key', models.CharField(max_length=1000, null=True)),
                ('consultado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fipe_name', models.CharField(max_length=1000, null=True)),
                ('nome', models.CharField(max_length=1000, null=True)),
                ('key', models.CharField(max_length=1000, null=True)),
                ('consultado', models.BooleanField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fipe.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(max_length=200)),
                ('fipe_codigo', models.CharField(max_length=1000, null=True)),
                ('nome', models.CharField(max_length=1000, null=True)),
                ('key', models.CharField(max_length=1000, null=True)),
                ('marca', models.CharField(max_length=1000, null=True)),
                ('preco', models.CharField(max_length=1000, null=True)),
                ('ano', models.CharField(max_length=1000, null=True)),
                ('consultado', models.BooleanField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fipe.Veiculo')),
            ],
        ),
    ]
